// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DiagnoseIncidentStateChangeEventPayload The event data structure
//
// swagger:model DiagnoseIncidentStateChangeEventPayload
type DiagnoseIncidentStateChangeEventPayload struct {

	// The involved resource data for the event
	DiagnoseIncident *DiagnoseIncident `json:"diagnoseIncident,omitempty"`
}

// Validate validates this diagnose incident state change event payload
func (m *DiagnoseIncidentStateChangeEventPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDiagnoseIncident(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiagnoseIncidentStateChangeEventPayload) validateDiagnoseIncident(formats strfmt.Registry) error {
	if swag.IsZero(m.DiagnoseIncident) { // not required
		return nil
	}

	if m.DiagnoseIncident != nil {
		if err := m.DiagnoseIncident.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("diagnoseIncident")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("diagnoseIncident")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this diagnose incident state change event payload based on the context it is used
func (m *DiagnoseIncidentStateChangeEventPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDiagnoseIncident(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiagnoseIncidentStateChangeEventPayload) contextValidateDiagnoseIncident(ctx context.Context, formats strfmt.Registry) error {

	if m.DiagnoseIncident != nil {

		if swag.IsZero(m.DiagnoseIncident) { // not required
			return nil
		}

		if err := m.DiagnoseIncident.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("diagnoseIncident")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("diagnoseIncident")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DiagnoseIncidentStateChangeEventPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiagnoseIncidentStateChangeEventPayload) UnmarshalBinary(b []byte) error {
	var res DiagnoseIncidentStateChangeEventPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
