// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResolveIncidentCreateEventPayload The event data structure
//
// swagger:model ResolveIncidentCreateEventPayload
type ResolveIncidentCreateEventPayload struct {

	// The involved resource data for the event
	ResolveIncident *ResolveIncident `json:"resolveIncident,omitempty"`
}

// Validate validates this resolve incident create event payload
func (m *ResolveIncidentCreateEventPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResolveIncident(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResolveIncidentCreateEventPayload) validateResolveIncident(formats strfmt.Registry) error {
	if swag.IsZero(m.ResolveIncident) { // not required
		return nil
	}

	if m.ResolveIncident != nil {
		if err := m.ResolveIncident.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resolveIncident")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resolveIncident")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this resolve incident create event payload based on the context it is used
func (m *ResolveIncidentCreateEventPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateResolveIncident(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResolveIncidentCreateEventPayload) contextValidateResolveIncident(ctx context.Context, formats strfmt.Registry) error {

	if m.ResolveIncident != nil {

		if swag.IsZero(m.ResolveIncident) { // not required
			return nil
		}

		if err := m.ResolveIncident.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resolveIncident")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resolveIncident")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResolveIncidentCreateEventPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResolveIncidentCreateEventPayload) UnmarshalBinary(b []byte) error {
	var res ResolveIncidentCreateEventPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
