// Code generated by go-swagger; DO NOT EDIT.

package incident

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RetrieveIncidentHandlerFunc turns a function with the right signature into a retrieve incident handler
type RetrieveIncidentHandlerFunc func(RetrieveIncidentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveIncidentHandlerFunc) Handle(params RetrieveIncidentParams) middleware.Responder {
	return fn(params)
}

// RetrieveIncidentHandler interface for that can handle valid retrieve incident params
type RetrieveIncidentHandler interface {
	Handle(RetrieveIncidentParams) middleware.Responder
}

// NewRetrieveIncident creates a new http.Handler for the retrieve incident operation
func NewRetrieveIncident(ctx *middleware.Context, handler RetrieveIncidentHandler) *RetrieveIncident {
	return &RetrieveIncident{Context: ctx, Handler: handler}
}

/*
	RetrieveIncident swagger:route GET /incident/{id} incident retrieveIncident

# Retrieves a Incident by ID

This operation retrieves a Incident entity. Attribute selection is enabled for all first level attributes.
*/
type RetrieveIncident struct {
	Context *middleware.Context
	Handler RetrieveIncidentHandler
}

func (o *RetrieveIncident) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRetrieveIncidentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
