# Use the official Golang image to create a build artifact.
# This is the development stage where we include tools like Air for live reloading.
FROM golang:1.21 AS development

# Set the environment variable to ensure Go modules are always used.
ENV GO111MODULE=on

# Install git, required if your dependencies need to be fetched via git.
# This step is needed if you decide to build Air from source or if your Go project has dependencies that need to be fetched via git.
RUN apt-get update && apt-get install -y git
RUN apt-get install ca-certificates

# Set the working directory inside the container.
WORKDIR /app

# Add the Go bin directory to the PATH so we can run Air directly.
ENV PATH="/go/bin:${PATH}"

# Copy go.mod and go.sum files first to leverage Docker cache.
COPY go.mod go.sum ./

# Download all dependencies.
RUN go mod download

# Install Air for live reloading using a known stable version.
# Replace 'v1.27.3' with the latest stable version as necessary.
RUN go install github.com/cosmtrek/air@v1.27.3

# Copy the source from the current directory to the Working Directory inside the container.
COPY . .

COPY cmd/tmf724incident-server/cert.pem /etc/ssl/certs/tmf724incident/cert.pem
COPY cmd/tmf724incident-server/key.pem /etc/ssl/private/tmf724incident/key.pem
# Set the working directory to the server directory where main.go is located.
WORKDIR /app/cmd/tmf724incident-server

# Set the environment variables to point to the certs.
ENV SSL_CERT_FILE=/etc/ssl/certs/cert.pem
ENV SSL_KEY_FILE=/etc/ssl/private/key.pem

EXPOSE 3030

# Command to run the executable with Air for live reloading.
CMD ["air"]