version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - GIN_MODE=debug
      - SSL_CERT_FILE=/etc/ssl/certs/cert.pem
      - SSL_KEY_FILE=/etc/ssl/private/key.pem
    volumes:
      - ./cmd/tmf724incident-server/cert.pem:/etc/ssl/certs/cert.pem
      - ./cmd/tmf724incident-server/key.pem:/etc/ssl/private/key.pem