// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IncidentStateChangeEventPayload The event data structure
//
// swagger:model IncidentStateChangeEventPayload
type IncidentStateChangeEventPayload struct {

	// The involved resource data for the event
	Incident *Incident `json:"incident,omitempty"`
}

// Validate validates this incident state change event payload
func (m *IncidentStateChangeEventPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIncident(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IncidentStateChangeEventPayload) validateIncident(formats strfmt.Registry) error {
	if swag.IsZero(m.Incident) { // not required
		return nil
	}

	if m.Incident != nil {
		if err := m.Incident.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("incident")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("incident")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this incident state change event payload based on the context it is used
func (m *IncidentStateChangeEventPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIncident(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IncidentStateChangeEventPayload) contextValidateIncident(ctx context.Context, formats strfmt.Registry) error {

	if m.Incident != nil {

		if swag.IsZero(m.Incident) { // not required
			return nil
		}

		if err := m.Incident.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("incident")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("incident")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IncidentStateChangeEventPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IncidentStateChangeEventPayload) UnmarshalBinary(b []byte) error {
	var res IncidentStateChangeEventPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
