// Code generated by go-swagger; DO NOT EDIT.

package events_subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fmilheir/final_year_project/backend/models"
)

// RegisterListenerCreatedCode is the HTTP code returned for type RegisterListenerCreated
const RegisterListenerCreatedCode int = 201

/*
RegisterListenerCreated Subscribed

swagger:response registerListenerCreated
*/
type RegisterListenerCreated struct {

	/*
	  In: Body
	*/
	Payload *models.EventSubscription `json:"body,omitempty"`
}

// NewRegisterListenerCreated creates RegisterListenerCreated with default headers values
func NewRegisterListenerCreated() *RegisterListenerCreated {

	return &RegisterListenerCreated{}
}

// WithPayload adds the payload to the register listener created response
func (o *RegisterListenerCreated) WithPayload(payload *models.EventSubscription) *RegisterListenerCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register listener created response
func (o *RegisterListenerCreated) SetPayload(payload *models.EventSubscription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterListenerCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterListenerBadRequestCode is the HTTP code returned for type RegisterListenerBadRequest
const RegisterListenerBadRequestCode int = 400

/*
RegisterListenerBadRequest Bad Request

swagger:response registerListenerBadRequest
*/
type RegisterListenerBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRegisterListenerBadRequest creates RegisterListenerBadRequest with default headers values
func NewRegisterListenerBadRequest() *RegisterListenerBadRequest {

	return &RegisterListenerBadRequest{}
}

// WithPayload adds the payload to the register listener bad request response
func (o *RegisterListenerBadRequest) WithPayload(payload *models.Error) *RegisterListenerBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register listener bad request response
func (o *RegisterListenerBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterListenerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterListenerUnauthorizedCode is the HTTP code returned for type RegisterListenerUnauthorized
const RegisterListenerUnauthorizedCode int = 401

/*
RegisterListenerUnauthorized Unauthorized

swagger:response registerListenerUnauthorized
*/
type RegisterListenerUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRegisterListenerUnauthorized creates RegisterListenerUnauthorized with default headers values
func NewRegisterListenerUnauthorized() *RegisterListenerUnauthorized {

	return &RegisterListenerUnauthorized{}
}

// WithPayload adds the payload to the register listener unauthorized response
func (o *RegisterListenerUnauthorized) WithPayload(payload *models.Error) *RegisterListenerUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register listener unauthorized response
func (o *RegisterListenerUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterListenerUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterListenerForbiddenCode is the HTTP code returned for type RegisterListenerForbidden
const RegisterListenerForbiddenCode int = 403

/*
RegisterListenerForbidden Forbidden

swagger:response registerListenerForbidden
*/
type RegisterListenerForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRegisterListenerForbidden creates RegisterListenerForbidden with default headers values
func NewRegisterListenerForbidden() *RegisterListenerForbidden {

	return &RegisterListenerForbidden{}
}

// WithPayload adds the payload to the register listener forbidden response
func (o *RegisterListenerForbidden) WithPayload(payload *models.Error) *RegisterListenerForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register listener forbidden response
func (o *RegisterListenerForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterListenerForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterListenerNotFoundCode is the HTTP code returned for type RegisterListenerNotFound
const RegisterListenerNotFoundCode int = 404

/*
RegisterListenerNotFound Not Found

swagger:response registerListenerNotFound
*/
type RegisterListenerNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRegisterListenerNotFound creates RegisterListenerNotFound with default headers values
func NewRegisterListenerNotFound() *RegisterListenerNotFound {

	return &RegisterListenerNotFound{}
}

// WithPayload adds the payload to the register listener not found response
func (o *RegisterListenerNotFound) WithPayload(payload *models.Error) *RegisterListenerNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register listener not found response
func (o *RegisterListenerNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterListenerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterListenerMethodNotAllowedCode is the HTTP code returned for type RegisterListenerMethodNotAllowed
const RegisterListenerMethodNotAllowedCode int = 405

/*
RegisterListenerMethodNotAllowed Method Not allowed

swagger:response registerListenerMethodNotAllowed
*/
type RegisterListenerMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRegisterListenerMethodNotAllowed creates RegisterListenerMethodNotAllowed with default headers values
func NewRegisterListenerMethodNotAllowed() *RegisterListenerMethodNotAllowed {

	return &RegisterListenerMethodNotAllowed{}
}

// WithPayload adds the payload to the register listener method not allowed response
func (o *RegisterListenerMethodNotAllowed) WithPayload(payload *models.Error) *RegisterListenerMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register listener method not allowed response
func (o *RegisterListenerMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterListenerMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterListenerConflictCode is the HTTP code returned for type RegisterListenerConflict
const RegisterListenerConflictCode int = 409

/*
RegisterListenerConflict Conflict

swagger:response registerListenerConflict
*/
type RegisterListenerConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRegisterListenerConflict creates RegisterListenerConflict with default headers values
func NewRegisterListenerConflict() *RegisterListenerConflict {

	return &RegisterListenerConflict{}
}

// WithPayload adds the payload to the register listener conflict response
func (o *RegisterListenerConflict) WithPayload(payload *models.Error) *RegisterListenerConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register listener conflict response
func (o *RegisterListenerConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterListenerConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterListenerInternalServerErrorCode is the HTTP code returned for type RegisterListenerInternalServerError
const RegisterListenerInternalServerErrorCode int = 500

/*
RegisterListenerInternalServerError Internal Server Error

swagger:response registerListenerInternalServerError
*/
type RegisterListenerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRegisterListenerInternalServerError creates RegisterListenerInternalServerError with default headers values
func NewRegisterListenerInternalServerError() *RegisterListenerInternalServerError {

	return &RegisterListenerInternalServerError{}
}

// WithPayload adds the payload to the register listener internal server error response
func (o *RegisterListenerInternalServerError) WithPayload(payload *models.Error) *RegisterListenerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register listener internal server error response
func (o *RegisterListenerInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterListenerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
