// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Incident
//
//	**TMF API Reference : TMF - 724 Incident**
//
//	**Release : 22.5 - November 2022**
//
//	The Incident API provides a standardized client interface to Incident Management Systems for creating, tracking and managing Incidents as a result of an issue or problem identified by a customer or another system.
//	Examples of Incident API originators (clients) include CRM applications, network management or fault management systems, or other Incident management systems (e.g. B2B).
//
//	The API supports the ability to send requests to create a new Incident specifying the nature and severity of the trouble or issue as well as all necessary related information. The API also includes mechanisms to search for and update existing Incidents. Notifications are defined to provide information when a Incident has been updated, including status changes. A basic set of states of a Incident has been specified (as an example) to handle Incident lifecycle management.
//	Incident API manages Incident resource:
//
//	  -	A Incident represents a record, or an issue raised by requestor that need to be solved, used for reporting and managing the resolution of problems, incidents or request -	The main Incident attributes are its name, priority, type,  dateTime attributes (occurTime, expected resolution, resolution), state and related information (change reason and change date), related parties (originator, owner, reviser, etc.), related entities (product, product order, customer bill) and notes Incident API performs the following operations on Incident -	Retrieval of an Incident or a collection of Incident depending on filter criteria -	Partial update of a Incident -	Creation of an Incident -	Notification of events on Incident: o	Incident state change o	Incident change o	Incident resolved o	Incident created o	Incident Information required
//
//
//
//	Copyright © TM Forum 2022. All Rights Reserved
//
//
//
//	Schemes:
//	  https
//	Host: localhost:8080
//	BasePath: /tmf-api/Incident/v4/
//	Version: 4.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
