// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListenToDiagnoseIncidentStateChangeEventHandlerFunc turns a function with the right signature into a listen to diagnose incident state change event handler
type ListenToDiagnoseIncidentStateChangeEventHandlerFunc func(ListenToDiagnoseIncidentStateChangeEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListenToDiagnoseIncidentStateChangeEventHandlerFunc) Handle(params ListenToDiagnoseIncidentStateChangeEventParams) middleware.Responder {
	return fn(params)
}

// ListenToDiagnoseIncidentStateChangeEventHandler interface for that can handle valid listen to diagnose incident state change event params
type ListenToDiagnoseIncidentStateChangeEventHandler interface {
	Handle(ListenToDiagnoseIncidentStateChangeEventParams) middleware.Responder
}

// NewListenToDiagnoseIncidentStateChangeEvent creates a new http.Handler for the listen to diagnose incident state change event operation
func NewListenToDiagnoseIncidentStateChangeEvent(ctx *middleware.Context, handler ListenToDiagnoseIncidentStateChangeEventHandler) *ListenToDiagnoseIncidentStateChangeEvent {
	return &ListenToDiagnoseIncidentStateChangeEvent{Context: ctx, Handler: handler}
}

/*
	ListenToDiagnoseIncidentStateChangeEvent swagger:route POST /listener/diagnoseIncidentStateChangeEvent notification listeners (client side) listenToDiagnoseIncidentStateChangeEvent

# Client listener for entity DiagnoseIncidentStateChangeEvent

Example of a client listener for receiving the notification DiagnoseIncidentStateChangeEvent
*/
type ListenToDiagnoseIncidentStateChangeEvent struct {
	Context *middleware.Context
	Handler ListenToDiagnoseIncidentStateChangeEventHandler
}

func (o *ListenToDiagnoseIncidentStateChangeEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListenToDiagnoseIncidentStateChangeEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
