// Code generated by go-swagger; DO NOT EDIT.

package diagnose_incident

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateDiagnoseIncidentHandlerFunc turns a function with the right signature into a create diagnose incident handler
type CreateDiagnoseIncidentHandlerFunc func(CreateDiagnoseIncidentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateDiagnoseIncidentHandlerFunc) Handle(params CreateDiagnoseIncidentParams) middleware.Responder {
	return fn(params)
}

// CreateDiagnoseIncidentHandler interface for that can handle valid create diagnose incident params
type CreateDiagnoseIncidentHandler interface {
	Handle(CreateDiagnoseIncidentParams) middleware.Responder
}

// NewCreateDiagnoseIncident creates a new http.Handler for the create diagnose incident operation
func NewCreateDiagnoseIncident(ctx *middleware.Context, handler CreateDiagnoseIncidentHandler) *CreateDiagnoseIncident {
	return &CreateDiagnoseIncident{Context: ctx, Handler: handler}
}

/*
	CreateDiagnoseIncident swagger:route POST /diagnoseIncident diagnoseIncident createDiagnoseIncident

# Creates a DiagnoseIncident

This operation creates a DiagnoseIncident entity.
*/
type CreateDiagnoseIncident struct {
	Context *middleware.Context
	Handler CreateDiagnoseIncidentHandler
}

func (o *CreateDiagnoseIncident) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateDiagnoseIncidentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
