// Code generated by go-swagger; DO NOT EDIT.

package resolve_incident

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListResolveIncidentHandlerFunc turns a function with the right signature into a list resolve incident handler
type ListResolveIncidentHandlerFunc func(ListResolveIncidentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListResolveIncidentHandlerFunc) Handle(params ListResolveIncidentParams) middleware.Responder {
	return fn(params)
}

// ListResolveIncidentHandler interface for that can handle valid list resolve incident params
type ListResolveIncidentHandler interface {
	Handle(ListResolveIncidentParams) middleware.Responder
}

// NewListResolveIncident creates a new http.Handler for the list resolve incident operation
func NewListResolveIncident(ctx *middleware.Context, handler ListResolveIncidentHandler) *ListResolveIncident {
	return &ListResolveIncident{Context: ctx, Handler: handler}
}

/*
	ListResolveIncident swagger:route GET /resolveIncident resolveIncident listResolveIncident

# List or find ResolveIncident objects

This operation list or find ResolveIncident entities
*/
type ListResolveIncident struct {
	Context *middleware.Context
	Handler ListResolveIncidentHandler
}

func (o *ListResolveIncident) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListResolveIncidentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
