// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListenToIncidentCreateEventHandlerFunc turns a function with the right signature into a listen to incident create event handler
type ListenToIncidentCreateEventHandlerFunc func(ListenToIncidentCreateEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListenToIncidentCreateEventHandlerFunc) Handle(params ListenToIncidentCreateEventParams) middleware.Responder {
	return fn(params)
}

// ListenToIncidentCreateEventHandler interface for that can handle valid listen to incident create event params
type ListenToIncidentCreateEventHandler interface {
	Handle(ListenToIncidentCreateEventParams) middleware.Responder
}

// NewListenToIncidentCreateEvent creates a new http.Handler for the listen to incident create event operation
func NewListenToIncidentCreateEvent(ctx *middleware.Context, handler ListenToIncidentCreateEventHandler) *ListenToIncidentCreateEvent {
	return &ListenToIncidentCreateEvent{Context: ctx, Handler: handler}
}

/*
	ListenToIncidentCreateEvent swagger:route POST /listener/incidentCreateEvent notification listeners (client side) listenToIncidentCreateEvent

# Client listener for entity IncidentCreateEvent

Example of a client listener for receiving the notification IncidentCreateEvent
*/
type ListenToIncidentCreateEvent struct {
	Context *middleware.Context
	Handler ListenToIncidentCreateEventHandler
}

func (o *ListenToIncidentCreateEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListenToIncidentCreateEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
