// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListenToResolveIncidentStateChangeEventHandlerFunc turns a function with the right signature into a listen to resolve incident state change event handler
type ListenToResolveIncidentStateChangeEventHandlerFunc func(ListenToResolveIncidentStateChangeEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListenToResolveIncidentStateChangeEventHandlerFunc) Handle(params ListenToResolveIncidentStateChangeEventParams) middleware.Responder {
	return fn(params)
}

// ListenToResolveIncidentStateChangeEventHandler interface for that can handle valid listen to resolve incident state change event params
type ListenToResolveIncidentStateChangeEventHandler interface {
	Handle(ListenToResolveIncidentStateChangeEventParams) middleware.Responder
}

// NewListenToResolveIncidentStateChangeEvent creates a new http.Handler for the listen to resolve incident state change event operation
func NewListenToResolveIncidentStateChangeEvent(ctx *middleware.Context, handler ListenToResolveIncidentStateChangeEventHandler) *ListenToResolveIncidentStateChangeEvent {
	return &ListenToResolveIncidentStateChangeEvent{Context: ctx, Handler: handler}
}

/*
	ListenToResolveIncidentStateChangeEvent swagger:route POST /listener/resolveIncidentStateChangeEvent notification listeners (client side) listenToResolveIncidentStateChangeEvent

# Client listener for entity ResolveIncidentStateChangeEvent

Example of a client listener for receiving the notification ResolveIncidentStateChangeEvent
*/
type ListenToResolveIncidentStateChangeEvent struct {
	Context *middleware.Context
	Handler ListenToResolveIncidentStateChangeEventHandler
}

func (o *ListenToResolveIncidentStateChangeEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListenToResolveIncidentStateChangeEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
