// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListenToResolveIncidentCreateEventHandlerFunc turns a function with the right signature into a listen to resolve incident create event handler
type ListenToResolveIncidentCreateEventHandlerFunc func(ListenToResolveIncidentCreateEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListenToResolveIncidentCreateEventHandlerFunc) Handle(params ListenToResolveIncidentCreateEventParams) middleware.Responder {
	return fn(params)
}

// ListenToResolveIncidentCreateEventHandler interface for that can handle valid listen to resolve incident create event params
type ListenToResolveIncidentCreateEventHandler interface {
	Handle(ListenToResolveIncidentCreateEventParams) middleware.Responder
}

// NewListenToResolveIncidentCreateEvent creates a new http.Handler for the listen to resolve incident create event operation
func NewListenToResolveIncidentCreateEvent(ctx *middleware.Context, handler ListenToResolveIncidentCreateEventHandler) *ListenToResolveIncidentCreateEvent {
	return &ListenToResolveIncidentCreateEvent{Context: ctx, Handler: handler}
}

/*
	ListenToResolveIncidentCreateEvent swagger:route POST /listener/resolveIncidentCreateEvent notification listeners (client side) listenToResolveIncidentCreateEvent

# Client listener for entity ResolveIncidentCreateEvent

Example of a client listener for receiving the notification ResolveIncidentCreateEvent
*/
type ListenToResolveIncidentCreateEvent struct {
	Context *middleware.Context
	Handler ListenToResolveIncidentCreateEventHandler
}

func (o *ListenToResolveIncidentCreateEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListenToResolveIncidentCreateEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
