// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListenToIncidentStateChangeEventHandlerFunc turns a function with the right signature into a listen to incident state change event handler
type ListenToIncidentStateChangeEventHandlerFunc func(ListenToIncidentStateChangeEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListenToIncidentStateChangeEventHandlerFunc) Handle(params ListenToIncidentStateChangeEventParams) middleware.Responder {
	return fn(params)
}

// ListenToIncidentStateChangeEventHandler interface for that can handle valid listen to incident state change event params
type ListenToIncidentStateChangeEventHandler interface {
	Handle(ListenToIncidentStateChangeEventParams) middleware.Responder
}

// NewListenToIncidentStateChangeEvent creates a new http.Handler for the listen to incident state change event operation
func NewListenToIncidentStateChangeEvent(ctx *middleware.Context, handler ListenToIncidentStateChangeEventHandler) *ListenToIncidentStateChangeEvent {
	return &ListenToIncidentStateChangeEvent{Context: ctx, Handler: handler}
}

/*
	ListenToIncidentStateChangeEvent swagger:route POST /listener/incidentStateChangeEvent notification listeners (client side) listenToIncidentStateChangeEvent

# Client listener for entity IncidentStateChangeEvent

Example of a client listener for receiving the notification IncidentStateChangeEvent
*/
type ListenToIncidentStateChangeEvent struct {
	Context *middleware.Context
	Handler ListenToIncidentStateChangeEventHandler
}

func (o *ListenToIncidentStateChangeEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListenToIncidentStateChangeEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
