// Code generated by go-swagger; DO NOT EDIT.

package incident

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateIncidentHandlerFunc turns a function with the right signature into a create incident handler
type CreateIncidentHandlerFunc func(CreateIncidentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateIncidentHandlerFunc) Handle(params CreateIncidentParams) middleware.Responder {
	return fn(params)
}

// CreateIncidentHandler interface for that can handle valid create incident params
type CreateIncidentHandler interface {
	Handle(CreateIncidentParams) middleware.Responder
}

// NewCreateIncident creates a new http.Handler for the create incident operation
func NewCreateIncident(ctx *middleware.Context, handler CreateIncidentHandler) *CreateIncident {
	return &CreateIncident{Context: ctx, Handler: handler}
}

/*
	CreateIncident swagger:route POST /incident incident createIncident

# Creates a Incident

This operation creates a Incident entity.
*/
type CreateIncident struct {
	Context *middleware.Context
	Handler CreateIncidentHandler
}

func (o *CreateIncident) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateIncidentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
